name: 'info-from-package-json'
description: 'Reads and outputs some information from package.json'
author: 'Myrotvorets'
inputs:
  workingdir:
    required: false
    description: 'Directory with package.json (default: current working directory)'
    default: ''

outputs:
  packageName:
    description: '`name` from `package.json`'
  packageVersion:
    description: '`version` from `package.json`'
  packageDescription:
    description: '`description` from `package.json`'
  packageHomepage:
    description: '`homepage` from `package.json`'
  packageBugsUrl:
    description: '`bugs.url` from `package.json`'
  packageScmUrl:
    description: '`repository.url` from `package.json`'

runs:
  using: 'node20'
  main: 'dist/index.js'
branding:
  color: blue
  icon: info
